/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conexionsqlserver.Validations;
import javax.swing.JOptionPane;
import conexionsqlserver.storedProcedures;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoséFrancisco
 */
public class adminMarcas extends javax.swing.JInternalFrame {
    /**
     * Creates new form adminMarcas
     */
    public adminMarcas() {
        initComponents();
        showMarca();
        showMarcaBaja();
    }
    
    static ResultSet res,con;
    public static int cod = 0;

    public static int getCod() {
        return cod;
    }

    public static void setCod(int cod) {
        adminMarcas.cod = cod;
    }
    
    public void showMarcaBaja(){
        DefaultTableModel marca = (DefaultTableModel) tableBajaMarcas.getModel();
        marca.setRowCount(0);
        res = conexionsqlserver.ConnectionDB.Query(
            "SELECT * FROM marca where marca.activo="+0+" order by nombre_marca"
        );
        
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt("cod_marca"));
                v.add(res.getString("nombre_marca"));
                marca.addRow(v);
                tableBajaMarcas.setModel(marca);
            }
        }
        catch(SQLException e){
        }
    }
    
    public void showMarca(){
        DefaultTableModel marca = (DefaultTableModel) tableMarca.getModel();
        marca.setRowCount(0);
        res = conexionsqlserver.ConnectionDB.Query(
            "SELECT * FROM marca where marca.activo="+1+" order by nombre_marca"
        );
        
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt("cod_marca"));
                v.add(res.getString("nombre_marca"));
                marca.addRow(v);
                tableMarca.setModel(marca);
            }
        }
        catch(SQLException e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtNewMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNuevaMarca = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMarca = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBajaMarcas = new javax.swing.JTable();
        btnHabilMarca = new javax.swing.JButton();

        setClosable(true);
        setTitle("Marcas");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar marcas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        btnActualizar.setBackground(new java.awt.Color(255, 51, 51));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(240, 240, 240));
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(240, 240, 240));
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(240, 240, 240));
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtNewMarca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtNewMarca.setForeground(new java.awt.Color(102, 102, 102));
        txtNewMarca.setEnabled(false);
        txtNewMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewMarcaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombre de la marca:");

        btnNuevaMarca.setBackground(new java.awt.Color(255, 51, 51));
        btnNuevaMarca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnNuevaMarca.setForeground(new java.awt.Color(240, 240, 240));
        btnNuevaMarca.setText("Nuevo");
        btnNuevaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMarcaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNewMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnNuevaMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(52, 52, 52)
                        .addComponent(btnNuevaMarca))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(btnActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar))
                        .addComponent(txtNewMarca)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaMarca)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcas en existencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        tableMarca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        tableMarca.setForeground(new java.awt.Color(102, 102, 102));
        tableMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableMarca.setRowHeight(35);
        tableMarca.setRowMargin(5);
        tableMarca.setShowVerticalLines(false);
        tableMarca.getTableHeader().setReorderingAllowed(false);
        tableMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMarcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMarca);
        if (tableMarca.getColumnModel().getColumnCount() > 0) {
            tableMarca.getColumnModel().getColumn(0).setMinWidth(0);
            tableMarca.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableMarca.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcas dadas de baja administrativamente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14), new java.awt.Color(255, 51, 51))); // NOI18N

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableBajaMarcas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        tableBajaMarcas.setForeground(new java.awt.Color(102, 102, 102));
        tableBajaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBajaMarcas.setRowHeight(35);
        tableBajaMarcas.setRowMargin(5);
        tableBajaMarcas.setShowVerticalLines(false);
        tableBajaMarcas.getTableHeader().setReorderingAllowed(false);
        tableBajaMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBajaMarcasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBajaMarcas);
        if (tableBajaMarcas.getColumnModel().getColumnCount() > 0) {
            tableBajaMarcas.getColumnModel().getColumn(0).setMinWidth(0);
            tableBajaMarcas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableBajaMarcas.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnHabilMarca.setBackground(new java.awt.Color(255, 51, 51));
        btnHabilMarca.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnHabilMarca.setForeground(new java.awt.Color(240, 240, 240));
        btnHabilMarca.setText("Habilitar");
        btnHabilMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHabilMarca.setEnabled(false);
        btnHabilMarca.setPreferredSize(new java.awt.Dimension(71, 25));
        btnHabilMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilMarcaActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnHabilMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(btnHabilMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHabilMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewMarcaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String marca  = txtNewMarca.getText();
        if( marca.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Ingresa el nombre de la marca", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else if( Validations.validarNombres(marca) ){
            JOptionPane.showMessageDialog(null, "Ingresa valores correctos", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else if( Validations.lenght(marca, 20) ){
            JOptionPane.showMessageDialog(null, "Máximo se aceptan 20 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else{
            if( Validations.existMarcaInactive(marca) ){
                JOptionPane.showMessageDialog(null, "Ya existe dicha marca, pero está dada de baja, te recomendamos que la habilites!!", "Información", JOptionPane.INFORMATION_MESSAGE);
                txtNewMarca.requestFocus();
            }
            else if( Validations.existMarcaActive(marca) ){
                JOptionPane.showMessageDialog(null, "Ya existe dicha marca, añade una diferente!!", "Información", JOptionPane.INFORMATION_MESSAGE);
                txtNewMarca.requestFocus();
            }
            else{
                try{
                    storedProcedures.addMarca(marca);
                    JOptionPane.showMessageDialog(null, "Marca almacenada exitosamente!!" , "Genial" , JOptionPane.INFORMATION_MESSAGE);
                    txtNewMarca.setText("");txtNewMarca.setEnabled(false);
                    btnGuardar.setEnabled(false);
                    showMarca();
                }
                catch( SQLException e ){
                    JOptionPane.showMessageDialog(this, "Hubo un error al almacenar la marca, intenta de nuevo", ":( FATAL!!", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tableMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMarcaMouseClicked
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(true);
        btnActualizar.setEnabled(true);
        txtNewMarca.setEnabled(true);
        
        try {
            int row = tableMarca.getSelectedRow();
            setCod(Integer.parseInt(tableMarca.getValueAt(row, 0).toString()));
            res = conexionsqlserver.ConnectionDB.Query("select * from marca where cod_marca="+getCod());
            while(res.next()){
                txtNewMarca.setText(res.getString("nombre_marca"));
            }
        } 
        catch (SQLException ex) {}
    }//GEN-LAST:event_tableMarcaMouseClicked

    private void btnNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMarcaActionPerformed
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(true);
        txtNewMarca.setText("");
        txtNewMarca.setEnabled(true);
        txtNewMarca.requestFocus();
        tableMarca.clearSelection();
    }//GEN-LAST:event_btnNuevaMarcaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "¿Estás seguro de dar de baja ésta marca?" , "Responder", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if( op == JOptionPane.NO_OPTION ){
            JOptionPane.showMessageDialog(null, "Proceso cancelado" , "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else{
            try{
                storedProcedures.deleteMarca(getCod());
                JOptionPane.showMessageDialog(null, "Baja exitosa!!", "Genial" , JOptionPane.INFORMATION_MESSAGE);
                txtNewMarca.setText("");txtNewMarca.setEnabled(false);
                showMarca();
                showMarcaBaja();
                btnActualizar.setEnabled(false);
                btnEliminar.setEnabled(false);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Huno un error, intenta de nuevo!!", "Error" , JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String marca  = txtNewMarca.getText();
        if( marca.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Ingresa el nuevo nombre de la marca", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else if( Validations.validarNombres(marca) ){
            JOptionPane.showMessageDialog(null, "Ingresa valores correctos", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else if( Validations.lenght(marca, 20) ){
            JOptionPane.showMessageDialog(null, "Máximo se aceptan 20 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            txtNewMarca.requestFocus();
        }
        else{
            if( Validations.existMarcaInactive(marca) ){
                JOptionPane.showMessageDialog(null, "Ya existe dicha marca, pero está dada de baja, te recomendamos que la habilites!!", "Información", JOptionPane.INFORMATION_MESSAGE);
                txtNewMarca.requestFocus();
            }
            else if( Validations.existMarcaActive(marca) ){
                JOptionPane.showMessageDialog(null, "Ya existe dicha marca, añade una diferente!!", "Información", JOptionPane.INFORMATION_MESSAGE);
                txtNewMarca.requestFocus();
            }
            else{
                try{
                    storedProcedures.updateMarca(getCod(), marca);
                    JOptionPane.showMessageDialog(null, "Marca actualizada exitosamente!!" , "Genial" , JOptionPane.INFORMATION_MESSAGE);
                    txtNewMarca.setText("");txtNewMarca.setEnabled(false);
                    btnGuardar.setEnabled(false);
                    btnEliminar.setEnabled(false);
                    btnActualizar.setEnabled(false);
                    showMarca();
                }
                catch( SQLException e ){
                    JOptionPane.showMessageDialog(this, "Hubo un error al actualizar la marca, intenta de nuevo", ":( FATAL!!", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnActualizar.setEnabled(false);
        txtNewMarca.setEnabled(false);
        txtNewMarca.setText("");
        tableMarca.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tableBajaMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBajaMarcasMouseClicked
        btnHabilMarca.setEnabled(true);
    }//GEN-LAST:event_tableBajaMarcasMouseClicked

    private void btnHabilMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilMarcaActionPerformed
        int row = tableBajaMarcas.getSelectedRow();
        int cod = Integer.parseInt(tableBajaMarcas.getValueAt(row, 0).toString());
        int opt = JOptionPane.showConfirmDialog(this, "¿Estás seguro de habilitar ésta marca?" , "¿Confirmar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if( opt == JOptionPane.NO_OPTION ){
            JOptionPane.showMessageDialog(null, "Proceso cancelado!!" , "Información", JOptionPane.INFORMATION_MESSAGE);
            tableBajaMarcas.clearSelection();
            btnHabilMarca.setEnabled(false);
        }
        else{
            try{
                storedProcedures.enableMarca(cod);
                JOptionPane.showMessageDialog(null, "Marca habilitada exitosamente!!" , "Genial", JOptionPane.INFORMATION_MESSAGE);
                tableBajaMarcas.clearSelection();
                btnHabilMarca.setEnabled(false);
                showMarcaBaja();
                showMarca();
            }
            catch( SQLException e ){}
        }
    }//GEN-LAST:event_btnHabilMarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHabilMarca;
    private javax.swing.JButton btnNuevaMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBajaMarcas;
    private javax.swing.JTable tableMarca;
    private javax.swing.JTextField txtNewMarca;
    // End of variables declaration//GEN-END:variables
}
