/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoséFrancisco
 */
public class mostrarCambios extends javax.swing.JInternalFrame {

    /**
     * Creates new form mostrarCambios
     */
    static ResultSet res;
    
    public void verCambios()
    {
        String nombreCli = null,
               appCli    = null,
               apmCli    = null,
               nCompleto = null,
               marca     = null,
               producto  = null,
               modelo    = null,
               pCompleto = null,
               fechaCam  = null,
               nuevoPro  = null,
               folioCam  = null,
               diferencia = null;
               
        
        String query = 
                "SELECT * FROM cambio"
                + " INNER JOIN cliente ON cambio.cod_cliente=cliente.cod_cliente"
                + " INNER JOIN producto ON cambio.cod_producto=producto.cod_producto"
                + " INNER JOIN marca_producto ON producto.cod_producto=marca_producto.cod_producto"
                + " INNER JOIN marca ON marca_producto.cod_marca=marca.cod_marca"
                + " INNER JOIN modelo_producto ON producto.cod_producto=modelo_producto.cod_producto"
                + " INNER JOIN modelo ON modelo_producto.cod_modelo=modelo.cod_modelo"
                ;
        
        res = conexionsqlserver.ConnectionDB.Query(query);
        
        try
        {
            while( res.next() )
            {
                nombreCli = res.getString("nombres_cliente");
                appCli    = res.getString("apellidop_cliente");
                apmCli    = res.getString("apellidom_cliente");
                nCompleto = nombreCli + " " + appCli + " " + apmCli;
                marca     = res.getString("nombre_marca");
                producto  = res.getString("nombre_producto");
                modelo    = res.getString("nombre_modelo");
                pCompleto = marca + " - " + producto + " - " + modelo;
                fechaCam  = res.getString("fecha_cambio");
                nuevoPro  = res.getString("nuevop_cambio");
                folioCam  = res.getString("folio_cambio");
                diferencia = res.getString("diferencia");
                
                Object fila[] = 
                {
                  fechaCam,
                  nCompleto,
                  pCompleto,
                  nuevoPro,
                  folioCam,
                  diferencia
                };
                
                DefaultTableModel td = (DefaultTableModel) tablaCambios.getModel();
                td.addRow(fila);
            }
        }
        catch( SQLException e ){}
    }
    
    public mostrarCambios() {
        initComponents();
        verCambios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCambios = new javax.swing.JTable();

        setClosable(true);
        setTitle("Historial de cambios");

        tablaCambios.setBackground(new java.awt.Color(240, 240, 240));
        tablaCambios.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        tablaCambios.setForeground(new java.awt.Color(0, 102, 204));
        tablaCambios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de cambio", "Cliente", "Producto Anterior", "Producto nuevo", "Folio de cambio", "Diferencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaCambios.setIntercellSpacing(new java.awt.Dimension(1, 3));
        tablaCambios.setRowHeight(30);
        tablaCambios.setShowVerticalLines(false);
        tablaCambios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCambios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCambios;
    // End of variables declaration//GEN-END:variables
}
