/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoséFrancisco
 */
public class mostrarDevoluciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form mostrarDevoluciones
     */
    static ResultSet res;
    public void verDevoluciones()
    {
        String nombreCli = null,
               appCli    = null,
               apmCli    = null,
               nCompleto = null,
               marca     = null,
               producto  = null,
               modelo    = null,
               pCompleto = null,
               fechaDev  = null,
               montoDev  = null;
               
        
        String query = 
                "SELECT * FROM devolucion"
                + " INNER JOIN cliente ON devolucion.cod_cliente=cliente.cod_cliente"
                + " INNER JOIN producto ON devolucion.cod_producto=producto.cod_producto"
                + " INNER JOIN marca_producto ON producto.cod_producto=marca_producto.cod_producto"
                + " INNER JOIN marca ON marca_producto.cod_marca=marca.cod_marca"
                + " INNER JOIN modelo_producto ON producto.cod_producto=modelo_producto.cod_producto"
                + " INNER JOIN modelo ON modelo_producto.cod_modelo=modelo.cod_modelo"
                ;
        
        res = conexionsqlserver.ConnectionDB.Query(query);
        
        try
        {
            while( res.next() )
            {
                nombreCli = res.getString("nombres_cliente");
                appCli    = res.getString("apellidop_cliente");
                apmCli    = res.getString("apellidom_cliente");
                nCompleto = nombreCli + " " + appCli + " " + apmCli;
                marca     = res.getString("nombre_marca");
                producto  = res.getString("nombre_producto");
                modelo    = res.getString("nombre_modelo");
                pCompleto = marca + " - " + producto + " - " + modelo;
                fechaDev  = res.getString("fecha_devolucion");
                montoDev  = res.getString("monto_devolucion");
                
                Object fila[] = 
                {
                  fechaDev,
                  nCompleto,
                  pCompleto,
                  montoDev
                };
                
                DefaultTableModel td = (DefaultTableModel) tablaDevolucion.getModel();
                td.addRow(fila);
            }
        }
        catch( SQLException e ){}
    }
    
    public mostrarDevoluciones() {
        initComponents();
        verDevoluciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDevolucion = new javax.swing.JTable();

        setClosable(true);
        setTitle("Historial de devoluciones");

        tablaDevolucion.setBackground(new java.awt.Color(240, 240, 240));
        tablaDevolucion.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        tablaDevolucion.setForeground(new java.awt.Color(0, 102, 204));
        tablaDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de devolución", "Cliente", "Producto", "Monto de devolución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaDevolucion.setIntercellSpacing(new java.awt.Dimension(1, 3));
        tablaDevolucion.setRowHeight(30);
        tablaDevolucion.setShowVerticalLines(false);
        tablaDevolucion.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDevolucion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDevolucion;
    // End of variables declaration//GEN-END:variables
}
