/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conexionsqlserver.storedProcedures;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author JoséFrancisco
 */
public class tableUsers extends javax.swing.JFrame {
    static ResultSet res;
    /**
     * Creates new form tableUsers
     */
    public tableUsers() {
        initComponents();
    }
    
    public void refresUsers(){
        DefaultTableModel modelo = (DefaultTableModel) tableShowUsers.getModel();
        modelo.setRowCount(0);
        res = conexionsqlserver.ConnectionDB.Query("select cod_user,username from usuario");
        
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                modelo.addRow(v);
                tableShowUsers.setModel(modelo);
            }
        }
        catch(SQLException e){
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowUsers = new javax.swing.JTable();
        deleteUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de usuarios");
        setBackground(new java.awt.Color(71, 47, 18));
        setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        setMinimumSize(new java.awt.Dimension(634, 482));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(634, 452));
        jPanel1.setLayout(null);

        tableShowUsers.setBackground(new java.awt.Color(240, 240, 240));
        tableShowUsers.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        tableShowUsers.setForeground(new java.awt.Color(102, 102, 102));
        tableShowUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableShowUsers.setMaximumSize(new java.awt.Dimension(300, 0));
        tableShowUsers.setMinimumSize(new java.awt.Dimension(300, 0));
        tableShowUsers.setRowHeight(35);
        tableShowUsers.setRowMargin(3);
        tableShowUsers.setShowVerticalLines(false);
        tableShowUsers.getTableHeader().setReorderingAllowed(false);
        tableShowUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableShowUsersMouseClicked(evt);
            }
        });
        tableShowUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableShowUsersKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableShowUsers);
        if (tableShowUsers.getColumnModel().getColumnCount() > 0) {
            tableShowUsers.getColumnModel().getColumn(0).setMinWidth(50);
            tableShowUsers.getColumnModel().getColumn(1).setMinWidth(100);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 90, 440, 309);

        deleteUser.setBackground(new java.awt.Color(255, 51, 51));
        deleteUser.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        deleteUser.setForeground(new java.awt.Color(250, 250, 250));
        deleteUser.setText("Eliminar Usuario");
        deleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUser.setEnabled(false);
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(deleteUser);
        deleteUser.setBounds(90, 410, 440, 27);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Usuarios");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 20, 160, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Selecciona el usuario a eliminar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 60, 190, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoTablaUsers.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 634, 452);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        
        int row = tableShowUsers.getSelectedRow();
        int opt = JOptionPane.showConfirmDialog(this, "¿Estás seguro de borrar dicho usuario?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(opt == JOptionPane.YES_OPTION){
            try{
                storedProcedures.eliminarUsuario(Integer.parseInt(tableShowUsers.getValueAt(row, 0).toString()));
                this.refresUsers();
            }
            catch(SQLException e){
            }
        }
    }//GEN-LAST:event_deleteUserActionPerformed

    private void tableShowUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableShowUsersKeyPressed
        deleteUser.setEnabled(true);
    }//GEN-LAST:event_tableShowUsersKeyPressed

    private void tableShowUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableShowUsersMouseClicked
        deleteUser.setEnabled(true);
    }//GEN-LAST:event_tableShowUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableShowUsers;
    // End of variables declaration//GEN-END:variables
}
